<a href="https://colab.research.google.com/github/mydesemberevil/Freecodecamp_Demographic_Data_Analyzer/blob/main/Ringkasan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import tensorflow as tf

x = tf.constant([[1., 2., 4.],
                 [4., 5., 6.]])

print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 2. 4.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [19]:
x @ tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[21., 38.],
       [38., 77.]], dtype=float32)>

In [15]:
tf.concat([x, x, x], axis=0)

<tf.Tensor: shape=(6, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [16]:
x = tf.cast(x, dtype=tf.float32)

tf.nn.softmax(x, axis=-1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.66524094],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)>

In [17]:
tf.nn.softmax(x, axis=-1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.66524094],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)>

In [20]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=22.0>

In [26]:
var = tf.Variable([0.0, 0.0, 0.0])
print(var)

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>


In [27]:
var.assign([1, 2, 3])
print(var)

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>


In [28]:
var.assign_add([1, 1, 1])
print(var)

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>


In [34]:
x = tf.Variable(1.0)

def f(x):
  y = x**2 + 2*x - 5
  return y

In [35]:
f(x)
print(f(x))

tf.Tensor(-2.0, shape=(), dtype=float32)


In [37]:
with tf.GradientTape() as tape:
  y = f(x)

g_x = tape.gradient(y, x)  # g(x) = dy/dx

print(g_x)

tf.Tensor(4.0, shape=(), dtype=float32)


In [38]:
@tf.function
def my_func(x):
  print('Tracing.\n')
  return tf.reduce_sum(x)

In [39]:
x = tf.constant([1, 2, 3])
my_func(x)

Tracing.



<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [41]:
# Inisialisasi tensor
a = tf.constant([1, 2, 3], dtype=tf.float64)

# Menghitung jumlah elemen di seluruh tensor
res = tf.reduce_sum(a)
print('Result: ', res)  # Output: tf.Tensor(10., shape=(), dtype=float64)

Result:  tf.Tensor(6.0, shape=(), dtype=float64)


In [42]:
@tf.function
def my_func(x):
  print('Tracing.\n')
  return tf.reduce_sum(x)

In [43]:
x = tf.constant([1, 2, 3])
my_func(x)

Tracing.



<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [44]:
x = tf.constant([10.0, 9.1, 8.2], dtype=tf.float32)
my_func(x)

Tracing.



<tf.Tensor: shape=(), dtype=float32, numpy=27.3>

In [45]:
class MyModule(tf.Module):
  def __init__(self, value):
    self.weight = tf.Variable(value)

  @tf.function
  def multiply(self, x):
    return x * self.weight

In [46]:
mod = MyModule(3)
mod.multiply(tf.constant([1, 2, 3]))

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9], dtype=int32)>

In [49]:
save_path = './saved'
tf.saved_model.save(mod, save_path)

In [48]:
reloaded = tf.saved_model.load(save_path)
reloaded.multiply(tf.constant([1, 2, 3]))

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9], dtype=int32)>

Pengantar Tensor


Tensor adalah array multi-dimensi dengan tipe seragam (disebut dtype ). Anda dapat melihat semua dtypes didukung di tf.dtypes.DType .

Jika Anda terbiasa dengan NumPy , tensor (semacam) seperti np.arrays .

Semua tensor tidak dapat diubah seperti angka dan string Python: Anda tidak akan pernah dapat memperbarui konten tensor, hanya membuat yang baru.

In [50]:
import tensorflow as tf
import numpy as np

In [51]:
# This will be an int32 tensor by default; see "dtypes" below.
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [54]:
rank_1_tensor = tf.constant([[2.0, 3.0, 4.0],
                            [5.0,6.0,7.0]])
print(rank_1_tensor)

tf.Tensor(
[[2. 3. 4.]
 [5. 6. 7.]], shape=(2, 3), dtype=float32)


In [55]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [57]:
# If you want to be specific, you can set the dtype (see below) at creation time
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [59]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[2, 3],
                 [3, 2]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[3 5]
 [6 6]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[2 6]
 [9 8]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 8  7]
 [18 17]], shape=(2, 2), dtype=int32) 



Tentang bentuk
Tensor memiliki bentuk. Beberapa kosakata:

Bentuk : Panjang (jumlah elemen) dari masing-masing sumbu tensor.
Rank : Jumlah sumbu tensor. Sebuah skalar memiliki rank 0, sebuah vektor memiliki rank 1, sebuah matriks memiliki rank 2.
Sumbu atau Dimensi : Dimensi tertentu dari sebuah tensor.
Ukuran : Jumlah total item dalam tensor, vektor bentuk produk.

In [62]:
rank_4_tensor = tf.zeros([2,3, 2, 4, 5])

In [63]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 5
Shape of tensor: (2, 3, 2, 4, 5)
Elements along axis 0 of tensor: 2
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  240


In [64]:
x = tf.constant([[1], [2], [3]])
print(x)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


In [65]:
reshaped = tf.reshape(x, [1, 3])

In [66]:
print(x)
print(reshaped)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [67]:
# Bad examples: don't do this

# You can't reorder axes with reshape.
print(tf.reshape(rank_3_tensor, [2, 3, 5]), "\n")

# This is a mess
print(tf.reshape(rank_3_tensor, [5, 6]), "\n")

# This doesn't work at all
try:
  tf.reshape(rank_3_tensor, [7, -1])
except Exception as e:
  print(f"{type(e).__name__}: {e}")

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]], shape=(2, 3, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]], shape=(5, 6), dtype=int32) 

InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 30 values, but the requested shape requires a multiple of 7 [Op:Reshape]
